[build]
builder = "nixpacks"
buildCommand = "npm run railway:setup"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/status"
healthcheckTimeout = 300

[postgres]
enabled = true
